services:
  server:
    build:
      context: ./
      dockerfile: ./cmd/server/Dockerfile
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"

  worker:
    build:
      context: ./
      dockerfile: ./cmd/worker/Dockerfile
    volumes:
      - ./data:/data

#volumes:
#  broker-db:
#    driver: local